version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5444:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=tikal_user
      - POSTGRES_DB=bff_workshop